global:
  postgresql:
    auth:
      postgresPassword: "agora-postgres-admin-2024"
      username: "agora"
      password: "agora-db-password-2024"
      database: "agora"

primary:
  nodeSelector:
    workload: database
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "database"
      effect: "NoSchedule"
  
  resources:
    requests:
      memory: "4Gi"
      cpu: "2"
    limits:
      memory: "8Gi"
      cpu: "4"
  
  persistence:
    enabled: true
    size: 50Gi
    storageClass: "local-path"
  
  # Enable pgvector extension
  initdb:
    scripts:
      init.sql: |
        -- Create pgvector extension
        CREATE EXTENSION IF NOT EXISTS vector;
        
        -- Note: Apache AGE requires manual installation
        -- Instructions: https://age.apache.org/
        
        -- Grant permissions
        GRANT ALL PRIVILEGES ON DATABASE agora TO agora;

readReplicas:
  replicaCount: 2
  nodeSelector:
    workload: database
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "database"
      effect: "NoSchedule"
  
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"
  
  persistence:
    enabled: true
    size: 50Gi
    storageClass: "local-path"

metrics:
  enabled: true

