mode: distributed

replicas: 4

persistence:
  enabled: true
  storageClass: local-path
  size: 300Gi

rootUser: minioadmin
rootPassword: agora-minio-password-2024

resources:
  requests:
    memory: 4Gi
    cpu: 2
  limits:
    memory: 8Gi
    cpu: 4

nodeSelector:
  workload: storage

tolerations:
  - key: "workload"
    operator: "Equal"
    value: "storage"
    effect: "NoSchedule"

consoleService:
  type: ClusterIP

service:
  type: ClusterIP
  port: 9000

buckets:
  - name: agora-user-uploads
    policy: none
    purge: false
  - name: agora-agent-artifacts
    policy: none
    purge: false
  - name: agora-voice-recordings
    policy: none
    purge: false
  - name: agora-screen-recordings
    policy: none
    purge: false
  - name: agora-exports
    policy: none
    purge: false

environment:
  MINIO_BROWSER: "on"
  MINIO_PROMETHEUS_AUTH_TYPE: "public"

